version: "3.2"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        networks:
            - linuxaspnetcore
        restart: unless-stopped
    db:
        image: "mcr.microsoft.com/mssql/server"
        restart: always
        environment:
            SA_PASSWORD: "password123"
            ACCEPT_EULA: "Y"
        volumes:
            - linuxaspnetcoredata:/var/opt/mssql
            
volumes:
  linuxaspnetcoredata:

networks:
  linuxaspnetcore:
     driver: bridge